site_name: Cadify User Manuals
nav:
  - Home: index.md
  
  - Documentation:
    - Cadify Light:
      - Getting Started: light/getting_started.md
      - Menu Elements: light/menu_elements.md
      - Task Pane Overview: taskPane/task_pane.md
      
    - Cadify:
      - Getting Started: cadify/getting_started.md
      - Menu Elements:
        - Overview: cadify/menu_elements/overview.md
        - File: cadify/menu_elements/filemenus.md
        - Tools: cadify/menu_elements/toolsMenu.md
        - Test: cadify/menu_elements/testMenu.md
      - Task Panes:
        - Model Tab: cadify/task_panes/modelTab.md
        - Drawing Tab: cadify/task_panes/drawingTab.md
        - Web Tab: cadify/task_panes/webTab.md
      - Cadify Product:
        - Create product: cadify/product/createProduct.md
        - Create drawing: cadify/product/createDrawing.md
        - Advanced:
          - Library Elements: cadify/product/library.md
          - Drawing Types: cadify/product/drawingTypes.md
          - Export Drawings: cadify/product/exportDrawings.md
    - Common:
      - Web Controls:
        - Available Controls: controls/cadifycontrols.md
        - Advanced: controls/cadifycontrols-advanced.md
      - Media Manager: mediaManager/MediaManager.md
      - Sketcher:
        - Sketcher Overview: sketcher/sketcher-overview.md
        - Advanced:
          - Sketcher Scroll-By: sketcher/advanced-sketcher-scrollby.md        
        - CadifySheet: sketcher/cadifysheet.md
        - CadifyLine: sketcher/cadifyline.md
        - CadifyRectangle: sketcher/cadifyrectangle.md
        - CadifyEllipse: sketcher/cadifyellipse.md
        - CadifyHoles: sketcher/cadifyholes.md
        - CadifyImage: sketcher/cadifyimage.md
        - CadifyDim: sketcher/cadifydim.md
        - CadifyText: sketcher/cadifytext.md
        - CadifyBezier: sketcher/cadifybezier.md
        - CadifySvg: sketcher/cadifysvg.md
        - CadifyJson: sketcher/cadifyjson.md
        - CadifyDartJson: sketcher/cadifydartjson.md
        - CadifyDartImage: sketcher/cadifydartimage.md
theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html