site_name: Cadify Light User Manual
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Docs:
      - Task Pane & Menu: task_pane.md
      - Product Management: product_management.md
      - Task Pane Deep Dive: taskpaneview_deepdive.md
      - Sketcher Overview: sketcher-overview.md
      - Cadify Line: cadifyline.md
theme:
  name: material
