site_name: Cadify Light User Manual
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Docs:
      - Menu: menu_elements.md
      - Task Pane Deep Dive: task_pane.md
      - Sketcher Overview: sketcher-overview.md
      - Cadify Line: cadifyline.md
theme:
  name: material
