site_name: Cadify Light User Manual
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Docs:
      - Menu Elements: menu_elements.md
      - Task Pane Overview: taskPane/task_pane.md
      - Web Controls: controls/cadifycontrols.md
      - Media Manager: mediaManager/MediaManager.md
      - Sketcher:
        - Sketcher Overview: sketcher/sketcher-overview.md
        - Advanced:
          - Sketcher Scroll-By: sketcher/advanced-sketcher-scrollby.md        
        - CadifySheet: sketcher/cadifysheet.md
        - CadifyLine: sketcher/cadifyline.md
        - CadifyRectangle: sketcher/cadifyrectangle.md
        - CadifyEllipse: sketcher/cadifyellipse.md
        - CadifyHoles: sketcher/cadifyholes.md
        - CadifyImage: sketcher/cadifyimage.md
        - CadifyDim: sketcher/cadifydim.md
        - CadifyText: sketcher/cadifytext.md
        - CadifyBezier: sketcher/cadifybezier.md
        - CadifySvg: sketcher/cadifysvg.md
        - CadifyJson: sketcher/cadifyjson.md
        - CadifyDartJson: sketcher/cadifydartjson.md
        - CadifyDartImage: sketcher/cadifydartimage.md
theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables